name: Test
on:
  push:

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node Environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - name: Install Dependencies
        run: npm ci
      - name: Check Formatting
        run: npm run format
      - name: Check Formatting
        run: npm run lint
      - name: Check Formatting
        run: npm run typecheck
      - name: Build Project
        run: npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: .next/
      - name: Run Unit Tests
        run: npm run Tests
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: coverage
          path: coverage/
      - name: Run E2E Tests
        run: npm run test:e2e
      - uses: actions/upload-artifact@v3
        with:
          name: report
          path: report/
